#!/bin/bash

IP=$(cat /etc/IP)
cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'

[[ ! -e /usr/lib/sshplus ]] && exit 0
tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-15s\n' "CREAR USUARIO TOKEN ID";tput sgr0

echo -ne "\033[1;32m🗣️ TOKEN ID:\033[1;37m ";read username
[[ -z $username ]] && {
	echo -e "\n${cor1}Token vacío o no válido!${scor}\n"
	exit 1
}
[[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
	echo -e "\n${cor1}Este token ya existe, intente con otro token!${scor}\n"
	exit 1
}
sizemin=$(echo ${#username})
[[ $sizemin -lt 2 ]] && {
	echo -e "\n${cor1}Ingresaste un token que es demasiado corto${scor}"
	echo -e "${cor1}utilizar al menos 2 caracteres!${scor}\n"
	exit 1
}
sizemax=$(echo ${#username})
[[ $sizemax -gt 25 ]] && {
	echo -e "\n${cor1}Ingresaste un token demasiado largo"
	echo -e "${cor1}utilizar un máximo de 25 caracteres!${scor}\n"
	exit 1
}
echo -ne "\033[1;32m🔑 CONTRASEÑA:\033[1;37m ";read password
[[ -z $password ]] && {
	echo -e "\n${cor1}Contraseña vacía o no válida!${scor}\n"
	exit 1
}
sizepass=$(echo ${#password})
[[ $sizepass -lt 4 ]] && {
	echo -e "\n${cor1}¡Contraseña corta!, utiliza al menos 4 caracteres${scor}\n"
	exit 1
}
echo -ne "\033[1;32m⌛ DÍAS PARA VENCER:\033[1;37m ";read dias
[[ -z $dias ]] && {
	echo -e "\n${cor1}Número de días vacíos!${scor}\n"
	exit 1
}
[[ ${dias} != ?(+|-)+([0-9]) ]] && {
	echo -e "\n${cor1}Ingresaste un número de días no válido!${scor}\n"
	exit 1
}
[[ $dias -lt 1 ]] && {
	echo -e "\n${cor1}El número debe ser mayor que cero.!${scor}\n"
	exit 1
}
echo -ne "\033[1;32m📲 LIMITE DE CONEXIONES:\033[1;37m ";read sshlimiter
[[ -z $sshlimiter ]] && {
	echo -e "\n${cor1}Dejaste el límite de conexión vacío!${scor}\n"
	exit 1
}
[[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
	echo -e "\n${cor1}Ingresaste un número no válido de conexiones!${scor}\n"
	exit 1
}
[[ $sshlimiter -lt 1 ]] && {
	echo -e "\n${cor1}El número de conexiones simultáneas debe ser mayor que cero.!${scor}\n"
	exit 1
}
final=$(date "+%Y-%m-%d" -d "+$dias days")
gui=$(date "+%d/%m/%Y" -d "+$dias days")
pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
echo "$password" >/etc/SSHPlus/senha/$username
echo "$username $sshlimiter" >>/root/usuarios.db


clear
echo -e "\E[44;1;37m======🦸DATOS DE ACCESO🦸‍♀️======\E[0m"
echo -e "\033[1;32m 🗣️TOKEN ID: \033[1;37m$username"
echo -e "\033[1;32m 🔑CONTRASEÑA: \033[1;37m$password"
echo -e "\033[1;32m ⌛EXPIRA EN: \033[1;37m$gui"
echo -e "\033[1;32m 📲LIMITE DE CONEXION: \033[1;37m$sshlimiter"
